name: Build & Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish NuGet package?'
        required: true
        default: 'false'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      PROJECT_NAME: YahooQuotesObservable

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore --no-cache

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        shell: pwsh
        run: dotnet pack ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          --configuration Release `
          --no-restore --no-build `
          -o ./artifacts

      - name: NuGet login
        if: github.event.inputs.publish == 'true'
        id: login
        uses: NuGet/login@v1
        with:
          user: dshe

      - name: Push Package
        if: github.event.inputs.publish == 'true'
        shell: pwsh
        run: |
          $pkg = Get-ChildItem ./artifacts/*.nupkg |
            Where-Object { $_.Name -notlike "*.symbols.nupkg" } |
            Select-Object -First 1

          dotnet nuget push $pkg.FullName `
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
          --source https://api.nuget.org/v3/index.json `
          --skip-duplicate
